import type { PropertyAgent } from "@/types/property";

export const agents: Record<string, PropertyAgent> = {
  "agent-1": {
    id: "agent-1",
    name: "Ama Mensah",
    title: "Senior Luxury Advisor — Accra",
    avatar: "",
    verified: true,
    responseTime: "< 2 hours",
    listingsCount: 47,
    rating: 4.9,
    phone: "+233 24 255 0142",
    email: "ama@goldcoast-estates.com.gh",
  },
  "agent-2": {
    id: "agent-2",
    name: "Kwame Asante",
    title: "Commercial Properties Director",
    avatar: "",
    verified: true,
    responseTime: "< 4 hours",
    listingsCount: 32,
    rating: 4.8,
    phone: "+233 20 255 0167",
    email: "kwame@goldcoast-estates.com.gh",
  },
  "agent-3": {
    id: "agent-3",
    name: "Amara Osei",
    title: "Investment & Land Specialist",
    avatar: "",
    verified: true,
    responseTime: "< 1 hour",
    listingsCount: 58,
    rating: 5.0,
    phone: "+233 30 255 0198",
    email: "amara@goldcoast-estates.com.gh",
  },
};
