import type { Property } from "@/types/property";
import { IMAGES, luxuryUrl } from "@/config/images";
import { agents } from "./agents";

const img = (ids: readonly string[]) => ids.map((id) => luxuryUrl(id, 1400));

export const properties: Property[] = [
  {
    id: "1",
    slug: "east-legon-penthouse",
    title: "East Legon Sky Penthouse",
    description:
      "A striking contemporary penthouse with panoramic Accra skyline views. Floor-to-ceiling glazing, private rooftop terrace, and resort-style amenities in one of the capital's most sought-after enclaves.",
    type: "apartment",
    listingType: "sale",
    status: "for_sale",
    price: 8500000,
    currency: "GHS",
    location: {
      city: "Accra",
      area: "East Legon",
      country: "Ghana",
      address: "American House Road, Tower A",
      lat: 5.639,
      lng: -0.1547,
    },
    specs: {
      bedrooms: 4,
      bathrooms: 5,
      sqft: 4200,
      parking: 2,
      yearBuilt: 2022,
      furnished: true,
    },
    amenities: ["Rooftop terrace", "Concierge", "Pool", "Smart home", "Backup power"],
    images: img(IMAGES.penthouse),
    featured: true,
    verified: true,
    agent: agents["agent-1"],
    createdAt: "2025-11-01",
  },
  {
    id: "2",
    slug: "cantonments-garden-estate",
    title: "Cantonments Garden Estate",
    description:
      "An elegant family compound on half an acre in Cantonments. Mature tropical gardens, guest cottage, and classic Ghanaian-modern architecture ideal for diplomatic or executive residence.",
    type: "house",
    listingType: "sale",
    status: "for_sale",
    price: 12000000,
    currency: "GHS",
    location: {
      city: "Accra",
      area: "Cantonments",
      country: "Ghana",
      address: "15 Fifth Circular Road",
      lat: 5.5753,
      lng: -0.1717,
    },
    specs: {
      bedrooms: 6,
      bathrooms: 6,
      sqft: 7200,
      parking: 3,
      yearBuilt: 2018,
      furnished: false,
    },
    amenities: ["Swimming pool", "Guest cottage", "Generator", "24/7 security"],
    images: img(IMAGES.estate),
    featured: true,
    verified: true,
    agent: agents["agent-1"],
    createdAt: "2025-10-15",
  },
  {
    id: "3",
    slug: "airport-city-executive-office",
    title: "Airport City Executive Office",
    description:
      "Grade-A fitted office suite in Accra's premier business district. Dedicated reception, meeting rooms, and direct access to Kotoka International Airport and five-star hospitality.",
    type: "office",
    listingType: "rent",
    status: "for_rent",
    price: 85000,
    currency: "GHS",
    location: {
      city: "Accra",
      area: "Airport City",
      country: "Ghana",
      address: "Independence Avenue, Block C, Level 8",
      lat: 5.6037,
      lng: -0.187,
    },
    specs: {
      bedrooms: 0,
      bathrooms: 2,
      sqft: 3200,
      parking: 4,
      yearBuilt: 2021,
      furnished: true,
    },
    amenities: ["24/7 security", "Meeting rooms", "Fiber internet", "Backup power"],
    images: img(IMAGES.office),
    featured: true,
    verified: true,
    agent: agents["agent-2"],
    createdAt: "2025-12-01",
  },
  {
    id: "4",
    slug: "trasacco-valley-villa",
    title: "Trasacco Valley Villa",
    description:
      "Contemporary villa in Trasacco Valley with infinity pool, landscaped gardens, and uninterrupted views. Designed for discerning families seeking privacy within gated community living.",
    type: "villa",
    listingType: "sale",
    status: "for_sale",
    price: 18500000,
    currency: "GHS",
    location: {
      city: "Accra",
      area: "Trasacco Valley",
      country: "Ghana",
      address: "Trasacco Valley Estates, Plot 24",
      lat: 5.628,
      lng: -0.128,
    },
    specs: {
      bedrooms: 5,
      bathrooms: 6,
      sqft: 9800,
      parking: 4,
      yearBuilt: 2023,
      furnished: true,
    },
    amenities: ["Infinity pool", "Gated community", "Home cinema", "Staff quarters"],
    images: img(IMAGES.villa),
    featured: true,
    verified: true,
    agent: agents["agent-2"],
    createdAt: "2025-09-20",
  },
  {
    id: "5",
    slug: "airport-city-sky-residence",
    title: "Airport City Sky Residence",
    description:
      "Sophisticated three-bedroom residence in Accra's business hub. Panoramic city views, resort-style amenities, and minutes from Kotoka International Airport.",
    type: "apartment",
    listingType: "sale",
    status: "for_sale",
    price: 4200000,
    currency: "GHS",
    location: {
      city: "Accra",
      area: "Airport City",
      country: "Ghana",
      address: "Independence Avenue, Tower B",
      lat: 5.6037,
      lng: -0.187,
    },
    specs: {
      bedrooms: 3,
      bathrooms: 3,
      sqft: 2400,
      parking: 2,
      yearBuilt: 2023,
      furnished: true,
    },
    amenities: ["Pool", "Gym", "Concierge", "Rooftop lounge"],
    images: img(IMAGES.accraApt),
    featured: true,
    verified: true,
    agent: agents["agent-3"],
    createdAt: "2025-11-20",
  },
  {
    id: "6",
    slug: "labone-executive-residence",
    title: "Labone Executive Residence",
    description:
      "Refined four-bedroom home in Labone with open-plan living, chef's kitchen, and lush courtyard. Walking distance to Osu and the diplomatic quarter.",
    type: "house",
    listingType: "sale",
    status: "pending",
    price: 6800000,
    currency: "GHS",
    location: {
      city: "Accra",
      area: "Labone",
      country: "Ghana",
      address: "Liberation Road",
      lat: 5.556,
      lng: -0.174,
    },
    specs: {
      bedrooms: 4,
      bathrooms: 4,
      sqft: 3800,
      parking: 2,
      yearBuilt: 2016,
      furnished: false,
    },
    amenities: ["Courtyard garden", "Generator", "Security post"],
    images: img(IMAGES.townhouse),
    featured: false,
    verified: true,
    agent: agents["agent-3"],
    createdAt: "2025-10-05",
  },
  {
    id: "7",
    slug: "osu-luxury-rental",
    title: "Osu Luxury Rental",
    description:
      "Fully furnished two-bedroom apartment in the heart of Osu. Modern finishes, dedicated parking, and proximity to restaurants, galleries, and the coastline.",
    type: "rental",
    listingType: "rent",
    status: "for_rent",
    price: 28000,
    currency: "GHS",
    location: {
      city: "Accra",
      area: "Osu",
      country: "Ghana",
      address: "Oxford Street",
      lat: 5.556,
      lng: -0.182,
    },
    specs: {
      bedrooms: 2,
      bathrooms: 2,
      sqft: 1650,
      parking: 1,
      yearBuilt: 2020,
      furnished: true,
    },
    amenities: ["Furnished", "Backup power", "Secure parking"],
    images: img(IMAGES.rental),
    featured: false,
    verified: true,
    agent: agents["agent-1"],
    createdAt: "2025-12-10",
  },
  {
    id: "8",
    slug: "tema-community-25-land",
    title: "Tema Community 25 Development Land",
    description:
      "1.8-acre parcel in Tema Community 25 with approved residential zoning. Ideal for boutique estate development. Full documentation and clear title.",
    type: "land",
    listingType: "sale",
    status: "for_sale",
    price: 3200000,
    currency: "GHS",
    location: {
      city: "Tema",
      area: "Community 25",
      country: "Ghana",
      address: "Devtraco Estates Road",
      lat: 5.669,
      lng: -0.012,
    },
    specs: {
      bedrooms: 0,
      bathrooms: 0,
      sqft: 78408,
      parking: 0,
      yearBuilt: 0,
      furnished: false,
    },
    amenities: ["Approved zoning", "Road access", "Utilities on site"],
    images: img(IMAGES.land),
    featured: false,
    verified: true,
    agent: agents["agent-3"],
    createdAt: "2025-08-15",
  },
];

export function getPropertyBySlug(slug: string): Property | undefined {
  return properties.find((p) => p.slug === slug);
}

export function getFeaturedProperties(): Property[] {
  return properties.filter((p) => p.featured);
}

export function getPropertiesByType(type: Property["type"]): Property[] {
  return properties.filter((p) => p.type === type);
}
