import type { Property } from "@/types/property";
import { IMAGES, luxuryUrl } from "@/config/images";
import { agents } from "./agents";

const img = (ids: readonly string[]) => ids.map((id) => luxuryUrl(id));

export const properties: Property[] = [
  {
    id: "1",
    slug: "penthouse-88-park-avenue",
    title: "Penthouse at 88 Park Avenue",
    description:
      "An extraordinary full-floor penthouse commanding panoramic views of Central Park. Floor-to-ceiling windows, private terrace, and bespoke Italian finishes define this architectural masterpiece.",
    type: "apartment",
    listingType: "sale",
    status: "for_sale",
    price: 12500000,
    currency: "USD",
    location: {
      city: "New York",
      area: "Upper East Side",
      country: "USA",
      address: "88 Park Avenue, Penthouse",
      lat: 40.7736,
      lng: -73.9566,
    },
    specs: {
      bedrooms: 4,
      bathrooms: 5,
      sqft: 6200,
      parking: 2,
      yearBuilt: 2019,
      furnished: true,
    },
    amenities: [
      "Private terrace",
      "Concierge",
      "Wine cellar",
      "Smart home",
      "Gym access",
    ],
    images: img(IMAGES.penthouse),
    featured: true,
    verified: true,
    agent: agents["agent-1"],
    createdAt: "2025-11-01",
  },
  {
    id: "2",
    slug: "belgravia-townhouse",
    title: "Belgravia Heritage Townhouse",
    description:
      "A meticulously restored Georgian townhouse in the heart of Belgravia. Six floors of refined living, private garden, and period details harmonized with contemporary luxury.",
    type: "house",
    listingType: "sale",
    status: "for_sale",
    price: 18750000,
    currency: "GBP",
    location: {
      city: "London",
      area: "Belgravia",
      country: "UK",
      address: "22 Eaton Square",
      lat: 51.4952,
      lng: -0.1557,
    },
    specs: {
      bedrooms: 6,
      bathrooms: 7,
      sqft: 8400,
      parking: 1,
      yearBuilt: 1842,
      furnished: false,
    },
    amenities: [
      "Private garden",
      "Wine room",
      "Staff quarters",
      "Original fireplaces",
    ],
    images: img(IMAGES.townhouse),
    featured: true,
    verified: true,
    agent: agents["agent-1"],
    createdAt: "2025-10-15",
  },
  {
    id: "3",
    slug: "difc-executive-suite",
    title: "DIFC Executive Office Suite",
    description:
      "Premium Grade-A office space in Dubai International Financial Centre. Floor-to-ceiling glass, dedicated reception, and direct access to metro and five-star hospitality.",
    type: "office",
    listingType: "rent",
    status: "for_rent",
    price: 45000,
    currency: "AED",
    location: {
      city: "Dubai",
      area: "DIFC",
      country: "UAE",
      address: "Gate Village 3, Level 42",
      lat: 25.2138,
      lng: 55.2824,
    },
    specs: {
      bedrooms: 0,
      bathrooms: 2,
      sqft: 4500,
      parking: 4,
      yearBuilt: 2021,
      furnished: true,
    },
    amenities: [
      "24/7 security",
      "Meeting rooms",
      "Pantry",
      "High-speed fiber",
    ],
    images: img(IMAGES.office),
    featured: true,
    verified: true,
    agent: agents["agent-2"],
    createdAt: "2025-12-01",
  },
  {
    id: "4",
    slug: "palm-jumeirah-villa",
    title: "Palm Jumeirah Beachfront Villa",
    description:
      "Contemporary beachfront villa with private beach access, infinity pool, and uninterrupted Arabian Gulf views. Designed for discerning families seeking privacy and resort living.",
    type: "villa",
    listingType: "sale",
    status: "for_sale",
    price: 22000000,
    currency: "AED",
    location: {
      city: "Dubai",
      area: "Palm Jumeirah",
      country: "UAE",
      address: "Frond M, Villa 12",
      lat: 25.1124,
      lng: 55.139,
    },
    specs: {
      bedrooms: 7,
      bathrooms: 8,
      sqft: 12500,
      parking: 4,
      yearBuilt: 2022,
      furnished: true,
    },
    amenities: [
      "Private beach",
      "Infinity pool",
      "Cinema room",
      "Staff villa",
      "Smart home",
    ],
    images: img(IMAGES.villa),
    featured: true,
    verified: true,
    agent: agents["agent-2"],
    createdAt: "2025-09-20",
  },
  {
    id: "5",
    slug: "airport-city-residence",
    title: "Airport City Sky Residence",
    description:
      "Sophisticated three-bedroom residence in Accra's premier business district. Panoramic city views, resort-style amenities, and proximity to Kotoka International Airport.",
    type: "apartment",
    listingType: "sale",
    status: "for_sale",
    price: 850000,
    currency: "USD",
    location: {
      city: "Accra",
      area: "Airport City",
      country: "Ghana",
      address: "Independence Avenue, Tower B",
      lat: 5.6037,
      lng: -0.187,
    },
    specs: {
      bedrooms: 3,
      bathrooms: 3,
      sqft: 2800,
      parking: 2,
      yearBuilt: 2023,
      furnished: true,
    },
    amenities: ["Pool", "Gym", "Concierge", "Rooftop lounge", "EV charging"],
    images: img(IMAGES.accraApt),
    featured: true,
    verified: true,
    agent: agents["agent-3"],
    createdAt: "2025-11-20",
  },
  {
    id: "6",
    slug: "cantonments-garden-estate",
    title: "Cantonments Garden Estate",
    description:
      "Expansive family estate on half an acre in Cantonments. Mature gardens, guest cottage, and timeless architecture ideal for diplomatic or executive residence.",
    type: "house",
    listingType: "sale",
    status: "pending",
    price: 1200000,
    currency: "USD",
    location: {
      city: "Accra",
      area: "Cantonments",
      country: "Ghana",
      address: "15 Fifth Circular Road",
      lat: 5.5753,
      lng: -0.1717,
    },
    specs: {
      bedrooms: 5,
      bathrooms: 5,
      sqft: 6500,
      parking: 3,
      yearBuilt: 2015,
      furnished: false,
    },
    amenities: ["Swimming pool", "Guest cottage", "Generator", "Security"],
    images: img(IMAGES.estate),
    featured: false,
    verified: true,
    agent: agents["agent-3"],
    createdAt: "2025-10-05",
  },
  {
    id: "7",
    slug: "brooklyn-heights-loft",
    title: "Brooklyn Heights Converted Loft",
    description:
      "Industrial-chic loft with 14-foot ceilings, exposed brick, and Brooklyn Bridge views. A rare offering in one of New York's most coveted neighborhoods.",
    type: "rental",
    listingType: "rent",
    status: "for_rent",
    price: 12500,
    currency: "USD",
    location: {
      city: "New York",
      area: "Brooklyn Heights",
      country: "USA",
      address: "45 Hicks Street",
      lat: 40.6962,
      lng: -73.994,
    },
    specs: {
      bedrooms: 2,
      bathrooms: 2,
      sqft: 2100,
      parking: 0,
      yearBuilt: 1920,
      furnished: true,
    },
    amenities: ["Doorman", "Roof deck", "In-unit laundry"],
    images: img(IMAGES.loft),
    featured: false,
    verified: true,
    agent: agents["agent-1"],
    createdAt: "2025-12-10",
  },
  {
    id: "8",
    slug: "east-legon-development-land",
    title: "East Legon Prime Development Land",
    description:
      "2.4-acre parcel in East Legon with approved residential zoning. Ideal for boutique development or private compound. Full documentation and clear title.",
    type: "land",
    listingType: "sale",
    status: "for_sale",
    price: 2400000,
    currency: "USD",
    location: {
      city: "Accra",
      area: "East Legon",
      country: "Ghana",
      address: "American House Road",
      lat: 5.639,
      lng: -0.1547,
    },
    specs: {
      bedrooms: 0,
      bathrooms: 0,
      sqft: 104544,
      parking: 0,
      yearBuilt: 0,
      furnished: false,
    },
    amenities: ["Approved zoning", "Road access", "Utilities nearby"],
    images: img(IMAGES.land),
    featured: false,
    verified: true,
    agent: agents["agent-3"],
    createdAt: "2025-08-15",
  },
];

export function getPropertyBySlug(slug: string): Property | undefined {
  return properties.find((p) => p.slug === slug);
}

export function getFeaturedProperties(): Property[] {
  return properties.filter((p) => p.featured);
}

export function getPropertiesByType(type: Property["type"]): Property[] {
  return properties.filter((p) => p.type === type);
}
